################################################################
# * Charge System Management Framework 
# * Sccsid @(#)Makefile	1.1 (Charge) 22/06/14
################################################################

LIB=svc
SRCS=ini.c util.c pidlist.c

clean: libclean

install:

.include <../charge.prog.mk>
.include <bsd.lib.mk>
