################################################################
# * Charge System Management Framework 
# * Sccsid @(#)Makefile	1.1 (Charge) 22/06/14
################################################################

PROG=svc.restartd
SRCS=main.c
MAN=

BINDIR= /libexec/svc

DPADD= ${LIBSVC}
LDADD= ${LIBSVC}

.include <../charge.prog.mk>
.include <bsd.prog.mk>
